### ISSUE TITLE
The System Itself

### ISSUE THREAD

**Issue by regularuser** [andrewhamili/CEUPreventiveMaintenanceSystem#1]
_When saving, it produces an error "Unable to convert Mysql date/time value to System.DateTime" but it is *_stored*\* in the database table of maintenance, column of 'date' as "0000-00-00"
***UPDATE: use custom date formatting if not implemented yet

**It is the same with adding/editing an equipment which causes to produce the same error when loading the data to the table therefore no data will be shown.

*Account Management is behind the main window when closed from the taskbar then clicked on Account Management button again, it says that the window was disposed

*In the main window, when you select "Makati" from the branch combo box, then you type an equipment name or equipment number, Manila branch is shown again

**Comment by andrewhamili** [comment]
Thank you for opening an issue. We will be resolving that issue ASAP. Please be patient.
